Repository Hebilicious/authjs-nuxt, pull requests merged in 2023-08, with the labels that each got.

#57 feat: add getProviders function to useAuth composable
  README.md
  docs/getting-started.md
  packages/authjs-nuxt/src/runtime/composables/useAuth.ts
  packages/authjs-nuxt/src/runtime/lib/client.ts
Labels: enhancement

#62 feat: add signin types
  packages/authjs-nuxt/package.json
  packages/authjs-nuxt/src/runtime/composables/useAuth.ts
  packages/authjs-nuxt/src/runtime/lib/client.ts
Labels: enhancement

#70 fix: generate correct useAuth types
  docs/getting-started.md
  packages/authjs-nuxt/src/nuxt-types.d.ts
  packages/authjs-nuxt/src/runtime/composables/useAuth.ts
  packages/authjs-nuxt/src/runtime/lib/client.d.ts
  packages/authjs-nuxt/src/runtime/lib/client.ts
  playgrounds/credentials/pages/index.vue
  playgrounds/credentials/server/api/auth/[...].ts
  playgrounds/credentials/types.d.ts
Labels: bug

#73 test: add basic integration test
  .gitignore
  package.json
  packages/authjs-nuxt/.npmrc
  playgrounds/credentials/.npmrc
  playgrounds/github/.npmrc
  playgrounds/keycloak/.npmrc
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test/basic.test.ts
  test/fixtures/basic/nuxt.config.ts
  test/fixtures/basic/package.json
  test/fixtures/basic/pages/index.vue
  test/fixtures/basic/pages/private.vue
  test/fixtures/basic/server/api/auth/[...].ts
  test/package.json
Labels: test
